CREATE TABLE MOVIE (
    MOVIE_TITLE VARCHAR(255) PRIMARY KEY,
    MOVIE_DESCRIPTION VARCHAR(255),
    MOVIE_RELEASE_YEAR NUMERIC(4),
    MOVIE_DURATION NUMERIC(5), 
    MOVIE_RATING NUMERIC(6) DEFAULT 0
);